[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings=[
    "@uniswap/v2-periphery=lib/v2-periphery",
    "@uniswap/v2-core=lib/v2-core",
    "@uniswap/v3-periphery/=lib/v3-periphery",
    "@uniswap/v3-core/=lib/v3-core",
    "@openzeppelin/=lib/openzeppelin-contracts"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config